[project]
name = "wikdict-reader"
version = "0.1.0"
description = "Annotate texts with translations"
authors = [
  {name = "Karl Bartel", email = "karl@karl.berlin"},
]
license = "MIT"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
