#!/usr/bin/python
import os
import sys

BASE_DIR = os.path.abspath(os.path.dirname(__file__) + '/..')

sys.path.insert(0, BASE_DIR + '/wsgi')
activate_this = BASE_DIR + '/venv/bin/activate_this.py'
exec(open(activate_this).read(), dict(__file__=activate_this))
os.environ['OPENSHIFT_DATA_DIR'] = BASE_DIR + '/data'
os.environ['OPENSHIFT_LOG_DIR'] = BASE_DIR + '/data'

import newrelic.agent
newrelic.agent.initialize()

from myapp import app as application
