# Copyright (c) 2021 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license, see file COPYING for the full text

name: Run tests

on:
- pull_request
- push

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2

      - name: Set up Python 3.9
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0
        with:
          python-version: '3.9'

      - name: Download necessary databases
        run: |-
          set -x
          for name in de de-en en en-de wikdict; do
            basename="${name}.sqlite3"
            wget -q -O "data/dict/${basename}" "https://download.wikdict.com/dictionaries/wdweb/${basename}"
          done

      - name: Run tests
        run: |-
          ./run_dev.sh test
