# Copyright (c) 2021 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license, see file COPYING for the full text

name: Run tests

on:
- pull_request
- push

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0

      - name: Set up Python 3.9
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1  # v4.7.0
        with:
          python-version: '3.9'

      - name: Download necessary databases
        run: |-
          set -x
          for name in de de-en en en-de wikdict; do
            basename="${name}.sqlite3"
            wget -q -O "data/dict/${basename}" "https://download.wikdict.com/dictionaries/wdweb/${basename}"
          done

      - name: Run tests
        run: |-
          ./run_dev.sh test
